# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'windows-latest'

stages:
  - stage: CheckoutCode
    jobs:
      - job: 'CheckoutGitCode'
        steps:
        - checkout: self

  - stage: Build
    jobs:
      - job: 'BuildJob'
        steps:
          - task: Maven@4
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'install'
              publishJUnitResults: true  # Enable this if you have unit tests
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false

  - stage: PublishArtifact
    jobs:
      - job: 'PublishArtifactJob'
        steps:
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifact: 'DemoArtifact'  # Corrected the artifact name
            publishLocation: 'pipeline'

  - stage: DownloadArtifact
    jobs:
      - deployment: Stage
        environment: DevTest-Stage
        strategy:
          runOnce:
            deploy:
              steps:
              - task: DownloadPipelineArtifact@2
                inputs:
                  buildType: 'specific'
                  project: '7e8c8f03-d3cd-4873-b071-549048546679'  # Replace with your project ID
                  definition: '24'  # Replace with your definition ID
                  buildVersionToDownload: 'latest'
                  artifactName: 'DemoArtifact'
                  targetPath: '$(Pipeline.Workspace)'
