# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  vmImage: Windows-latest

stages:
  - stage: CheckoutCode
    jobs: 
      - job: 'CheckoutGitCode'
        steps:
           - checkout: self
  - stage: Build
    jobs:
      - job: "BuildJob"
        steps:
          - task: Maven@4
            inputs:
               mavenPomFile: 'pom.xml'
               goals: 'install'
               publishJUnitResults: false
               javaHomeOption: 'JDKVersion'
               mavenVersionOption: 'Default'
               mavenAuthenticateFeed: false
               effectivePomSkip: false
               sonarQubeRunAnalysis: false

  - stage: PublishArtifact
    jobs:
      - job: 'Publish_artifactjob'
        steps:
        - task: PublishPipelineArtifact@1
          inputs:
           targetPath: '$(Pipeline.Workspace)'
           artifact: 'DemoArtifactyml'
           publishLocation: 'pipeline'

  - stage: DownloadArtifact
    jobs:
      - deployment: Stage
        environment: Stage
        strategy:
         runOnce:
           deploy:
             steps:
             - task: DownloadPipelineArtifact@2
               inputs:
                buildType: 'specific'
                project: '7e8c8f03-d3cd-4873-b071-549048546679'
                definition: '24'
                buildVersionToDownload: 'latest'
                artifactName: 'DemoArtifactyml'
                targetPath: '$(Pipeline.Workspace)'

